var _ = require('./')

// add functions that return wrapped values when chaining
require('./function/after')
require('./object/assign')
require('./collection/at')
require('./function/bind')
require('./function/bindAll')
require('./function/bindKey')
require('./array/compact')
require('./function/compose')
require('./collection/countBy')
require('./function/debounce')
require('./object/defaults')
require('./function/defer')
require('./function/delay')
require('./array/difference')
require('./collection/filter')
require('./array/flatten')
require('./collection/forEach')
require('./object/forIn')
require('./object/forOwn')
require('./object/functions')
require('./collection/groupBy')
require('./array/initial')
require('./array/intersection')
require('./object/invert')
require('./collection/invoke')
require('./object/keys')
require('./collection/map')
require('./collection/max')
require('./function/memoize')
require('./object/merge')
require('./collection/min')
require('./array/object')
require('./object/omit')
require('./function/once')
require('./object/pairs')
require('./function/partial')
require('./function/partialRight')
require('./object/pick')
require('./array/pluck')
require('./array/range')
require('./collection/reject')
require('./array/rest')
require('./collection/shuffle')
require('./collection/sortBy')
require('./chaining/tap')
require('./function/throttle')
require('./utility/times')
require('./collection/toArray')
require('./array/union')
require('./array/uniq')
require('./object/values')
require('./collection/where')
require('./array/without')
require('./function/wrap')
require('./array/zip')

// // add aliases
require('./collection/collect')
require('./array/drop')
require('./collection/each')
require('./object/extend')
require('./object/methods')
require('./collection/select')
require('./array/tail')
require('./array/unique')


// /*--------------------------------------------------------------------------*/

// // add functions that return unwrapped values when chaining
require('./object/clone')
require('./object/cloneDeep')
require('./collection/contains')
require('./utility/escape')
require('./collection/every')
require('./collection/find')
require('./object/has')
require('./utility/identity')
require('./array/indexOf')
require('./object/isArguments')
require('./object/isArray')
require('./object/isBoolean')
require('./object/isDate')
require('./object/isElement')
require('./object/isEmpty')
require('./object/isEqual')
require('./object/isFinite')
require('./object/isFunction')
require('./object/isNaN')
require('./object/isNull')
require('./object/isNumber')
require('./object/isObject')
require('./object/isPlainObject')
require('./object/isRegExp')
require('./object/isString')
require('./object/isUndefined')
require('./array/lastIndexOf')
require('./utility/mixin')
require('./utility/noConflict')
require('./utility/random')
require('./collection/reduce')
require('./collection/reduceRight')
require('./utility/result')
require('./collection/size')
require('./collection/some')
require('./array/sortedIndex')
require('./utility/template')
require('./utility/unescape')
require('./utility/uniqueId')

// // add aliases
require('./collection/all')
require('./collection/any')
require('./collection/detect')
require('./collection/foldl')
require('./collection/foldr')
require('./collection/include')
require('./collection/inject')

// add functions capable of returning wrapped and unwrapped values when chaining
require('./array/first')
require('./array/last')
// add aliases
require('./array/take')
require('./array/head')

module.exports = _
